import type { Metadata } from "next"
import { GeistSans } from "geist/font/sans"

import "./globals.css"

import { cn } from "@/lib/utils"

const fontSans = GeistSans

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("font-sans antialiased", fontSans.variable)}>
        {children}
      </body>
    </html>
  )
}
